sonar.projectKey=nahushr_ThreadCraft
sonar.organization=nahushr
sonar.projectName=ThreadCraft
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.sources=src,examples/vite/src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/data/emojis.json,**/dist/**,**/node_modules/**
sonar.coverage.exclusions=**
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=600
