import { StyleSheet } from "react-native";

export const nativeStyles = StyleSheet.create({
  root: { width: "100%", gap: 14 },
  chatRoot: { flex: 1, height: "100%", gap: 0, backgroundColor: "#f8fafc" },
  chatStream: { flex: 1, minHeight: 0 },
  chatStreamContent: { gap: 14, paddingHorizontal: 14, paddingVertical: 12 },
  header: { position: "relative", flexDirection: "row", justifyContent: "space-between", gap: 16, padding: 20, borderWidth: 1, borderColor: "#e4e7ec", borderRadius: 16, backgroundColor: "#fff" },
  headerContent: { flex: 1, minWidth: 0, gap: 8 },
  eyebrow: { color: "#315efb", fontSize: 11, fontWeight: "800", letterSpacing: 1.1 },
  title: { color: "#182230", fontSize: 21, fontWeight: "800" },
  headerBody: { color: "#475467", fontSize: 14, lineHeight: 21 },
  detailRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 8, marginTop: 2 },
  detail: { color: "#667085", fontSize: 12 },
  status: { overflow: "hidden", paddingHorizontal: 9, paddingVertical: 4, borderRadius: 20, color: "#067647", backgroundColor: "#ecfdf3", fontSize: 11, fontWeight: "700" },
  externalLink: { alignSelf: "flex-start", color: "#315efb", fontSize: 12, fontWeight: "700" },
  streamHeading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 2 },
  streamTitle: { color: "#182230", fontSize: 17, fontWeight: "800" },
  streamCount: { color: "#667085", fontSize: 12 },
  stream: { gap: 14 },
  empty: { padding: 24, borderWidth: 1, borderColor: "#eaecf0", borderRadius: 14, color: "#667085", backgroundColor: "#fff", textAlign: "center" },
  comment: { gap: 8 },
  chatMessage: { maxWidth: "100%" },
  chatMessageUser: { alignSelf: "flex-end", width: "100%", alignItems: "flex-end" },
  chatCardUser: { maxWidth: "88%", borderRadius: 18, borderTopRightRadius: 5, backgroundColor: "#315efb", borderColor: "#294ec5" },
  chatCardAssistant: { maxWidth: "88%", borderRadius: 18, borderTopLeftRadius: 5 },
  commentHeading: { minHeight: 40, flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 8 },
  avatar: { width: 36, height: 36, alignItems: "center", justifyContent: "center", overflow: "hidden", borderWidth: 1, borderColor: "#e4e7ec", borderRadius: 18, backgroundColor: "#eef2ff" },
  avatarImage: { width: 36, height: 36, borderRadius: 18 },
  avatarText: { color: "#315efb", fontSize: 12, fontWeight: "800" },
  author: { color: "#344054", fontSize: 13, fontWeight: "700" },
  authorBadge: { flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 8, paddingVertical: 3, borderWidth: 1, borderColor: "#e4e7ec", borderRadius: 20, backgroundColor: "#f2f4f7" },
  authorBadgeText: { color: "#475467", fontSize: 10, fontWeight: "700" },
  timestamp: { marginLeft: "auto", color: "#98a2b3", fontSize: 10 },
  card: { padding: 14, borderWidth: 1, borderColor: "#e4e7ec", borderRadius: 12, backgroundColor: "#fff" },
  commentText: { color: "#344054", fontSize: 14, lineHeight: 21 },
  rating: { flexDirection: "row", alignItems: "center", gap: 7, marginTop: 8 },
  ratingText: { color: "#f59e0b", fontSize: 15, letterSpacing: 1 },
  ratingValue: { color: "#667085", fontSize: 11, fontWeight: "700" },
  attachments: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 10 },
  attachment: { maxWidth: "100%", overflow: "hidden", paddingHorizontal: 10, paddingVertical: 7, borderWidth: 1, borderColor: "#e4e7ec", borderRadius: 9, backgroundColor: "#f9fafb" },
  attachmentImage: { width: 140, height: 100, marginBottom: 5, borderRadius: 6, backgroundColor: "#f2f4f7" },
  attachmentText: { color: "#475467", fontSize: 11 },
  actionRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 7, marginTop: 10 },
  action: { minHeight: 30, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 4, paddingHorizontal: 9, borderWidth: 1, borderColor: "#eaecf0", borderRadius: 18, backgroundColor: "#fff" },
  actionSelected: { borderColor: "#c7d2fe", backgroundColor: "#eef2ff" },
  actionText: { color: "#667085", fontSize: 11, fontWeight: "600" },
  replyAction: { paddingHorizontal: 9, paddingVertical: 6 },
  replyActionText: { color: "#667085", fontSize: 12, fontWeight: "600" },
  replies: { gap: 12, marginLeft: 16, paddingLeft: 12, borderLeftWidth: 2, borderLeftColor: "#eaecf0" },
  moreButton: { minHeight: 42, alignItems: "center", justifyContent: "center", paddingHorizontal: 14, borderWidth: 1, borderColor: "#d0d5dd", borderRadius: 10, backgroundColor: "#fff" },
  moreButtonText: { color: "#315efb", fontSize: 13, fontWeight: "700" },
  error: { color: "#b42318", fontSize: 12 },
  typingIndicator: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 13, paddingVertical: 10, borderWidth: 1, borderColor: "#e4e7ec", borderRadius: 15, borderBottomLeftRadius: 5, backgroundColor: "#fff" },
  typingText: { color: "#667085", fontSize: 12 },
  composer: { gap: 10, padding: 14, borderWidth: 1, borderColor: "#e4e7ec", borderRadius: 14, backgroundColor: "#fff" },
  replyBanner: { flexDirection: "row", alignItems: "center", gap: 8, padding: 10, borderLeftWidth: 3, borderLeftColor: "#315efb", borderRadius: 7, backgroundColor: "#f5f7ff" },
  replyBannerCopy: { flex: 1, gap: 2 },
  replyBannerTitle: { color: "#344054", fontSize: 11, fontWeight: "700" },
  replyBannerText: { color: "#667085", fontSize: 11 },
  identityField: { gap: 5 },
  fieldLabel: { color: "#475467", fontSize: 11, fontWeight: "700" },
  input: { minHeight: 40, paddingHorizontal: 10, paddingVertical: 8, borderWidth: 1, borderColor: "#d0d5dd", borderRadius: 9, color: "#182230", backgroundColor: "#fff", fontSize: 13 },
  textarea: { minHeight: 88, textAlignVertical: "top" },
  starRow: { flexDirection: "row", alignItems: "center" },
  starButton: { paddingHorizontal: 3, paddingVertical: 1 },
  starText: { color: "#f59e0b", fontSize: 25 },
  toolRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 8 },
  toolButton: { minHeight: 34, flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 10, borderWidth: 1, borderColor: "#e4e7ec", borderRadius: 9, backgroundColor: "#fff" },
  toolButtonText: { color: "#475467", fontSize: 11, fontWeight: "700" },
  sendButton: { minHeight: 40, alignItems: "center", justifyContent: "center", paddingHorizontal: 18, borderRadius: 9, backgroundColor: "#315efb" },
  sendDisabled: { opacity: 0.48 },
  sendText: { color: "#fff", fontSize: 12, fontWeight: "800" },
  flexSpacer: { flex: 1 },
  roleWrap: { position: "relative" },
  roleMenu: { position: "absolute", zIndex: 2, bottom: 40, left: 0, minWidth: 140, padding: 5, borderWidth: 1, borderColor: "#e4e7ec", borderRadius: 10, backgroundColor: "#fff", elevation: 4 },
  roleOption: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 7 },
  roleOptionSelected: { backgroundColor: "#eef2ff" },
  roleOptionText: { color: "#344054", fontSize: 12, fontWeight: "600" },
  selectedFiles: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  fileChip: { flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 20, backgroundColor: "#f2f4f7" },
  fileChipText: { maxWidth: 180, color: "#475467", fontSize: 10 },
  fileRemove: { color: "#b42318", fontSize: 14, fontWeight: "700" },
  modalBackdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(16, 24, 40, 0.42)" },
  emojiSheet: { maxHeight: "78%", padding: 16, borderTopLeftRadius: 18, borderTopRightRadius: 18, backgroundColor: "#fff" },
  emojiSheetHeading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 10 },
  emojiTitle: { color: "#182230", fontSize: 16, fontWeight: "800" },
  modalClose: { padding: 5 },
  modalCloseText: { color: "#667085", fontSize: 20 },
  categoryRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginBottom: 10 },
  categoryButton: { paddingHorizontal: 9, paddingVertical: 7, borderRadius: 18, backgroundColor: "#f2f4f7" },
  categorySelected: { backgroundColor: "#eef2ff" },
  categoryText: { color: "#475467", fontSize: 11, fontWeight: "600" },
  emojiGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "flex-start", paddingBottom: 24 },
  emojiButton: { width: 42, height: 42, alignItems: "center", justifyContent: "center" },
  emojiText: { fontSize: 24 },
});
